# Validate all YAML changes, e.g. http://lint.travis-ci.org/

sudo: required
language: python
cache: pip
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - pypy
  - pypy3
install:
  - pip install --upgrade pytest # needed for cases where there is already an old pytest installed
  - pip install pytest-cov       # needed for the codecov uploader
  - pip install -r requirements.txt -r tests/requirements.txt
before_script:
  - ./tests/wait-for-httpbin.sh
script:
  - pytest
